[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://delirious-ambiguity-willing.ngrok-free.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
